
 			<div  class= "col-xs-9 col-sm-9 col-md-9 col-lg-9">
 				<div class= "panel panel-primary">
 					
 						<div class="carousel-inner">


 						<div class="panel-body">
		 						
		 						<P ALIGN="justify"<big><b>Las ideas arraigadas en la mente influyen en la forma en que vemos a las personas y en cómo reaccionamos a determinadas situaciones. Diversos estudios han demostrado que la cultura influye en la forma en la que nuestro cerebro procesa la información y responde a los estímulos. Esta es otra de las razones por las que es tan importante.</big></b>
		 				</div>
		 				<div class="item active">
                                <img src="ejem.png" class="img-responsive img-full" >
                            </div>

                            	<P ALIGN="justify"<big><b>Cada uno de nosotros se siente representado por un grupo de tradiciones, elementos, formas de pensamiento, formas de actuar que son parte de la sociedad o del grupo social en el cual desarrollamos nuestra vida cotidiana y que nos dan una idea de pertenencia. De este modo, es muy difícil que alguien de nacionalidad alemana se sienta parte de la cultura india porque las representaciones culturales de cada sociedad son muy distintas y tienen que ver con las especificidades del lugar, del ambiente, del momento, del grupo social, etc.</big></b>
 						</div>


 					<div class="item active">
                             <img class="img-responsive img-full" src="est.jpg" alt="">
                    </div>
 					
 					<div class="panel-body">

<form class="form-horizontal" role="form" action="<?php  echo BASE_URL;?>persons/index"	method="post">
	
</form>
 					</div>
 				</div>
 		</div>
 			<!-- no borrar -->
 			</div>
 			
 		</div>
 	</div>

 	
 	
 				
 					
 					
 					
 					