
<div  class= "col-xs-9 col-sm-9 col-md-9 col-lg-9">
 				<div class= "panel panel-primary">
 					<div class= "panel-heading">
 						<h3 class= "panel-title"> Nueva Actividad </h3>
 					</div>
 					
 					<div class="panel-body">

<form class="form-horizontal" role="form" action="<?php  echo BASE_URL;?>actividad/insert" method="post">
	
	<div class="form-group">
		<label class="col-sm-3 control-label">Nombre de la Actividad:</label>
		<div class="col-sm-5">
			<input type="text" class="form-control" name="actividad" placeholder="Nombre" required> 
		</div>
	</div>

	
	<div class="form-group">
		<label class="col-sm-3 control-label">Fecha de inicio Actividad:</label>
		<div class="col-sm-5">
			<input type="datetime-local" class="form-control" name="fecha_inicio" placeholder="Fecha de inicio" required> 
		</div>
	</div>
	

	<div class="form-group">
		<label class="col-sm-3 control-label">Fecha de fin Actividad:</label>
		<div class="col-sm-5">
			<input type="datetime-local" class="form-control" name="fecha_fin" placeholder="Fecha de fin" required> 
		</div>
	</div>
	
	
	<div class="form-group">
		<label class="col-sm-3 control-label">Ubicacion:</label>
		<div class="col-sm-5">
			<input type="text" class="form-control" name="ubicacion" placeholder="Ubicacion" required> 
		</div>
	</div>
	
	<center>
		<br>
		<br>
		<input type="submit" class="btn btn-primary" value="Registrar">
	</center>
	

					
</form>
 					</div>
 				</div>
 		</div>
 			<!-- no borrar -->
 			</div>
 			
 		</div>
 	</div>

 	
 	
 				
 					
 					
 					
 					