
 			<div  class= "col-xs-9 col-sm-9 col-md-9 col-lg-9">
 				<div class= "panel panel-primary">
 					<div class= "panel-heading">
 						<h3 class= "panel-title"> NOMBRE DEL MODULO </h3>
 					</div>
 					
 					<div class="panel-body">

<form class="form-horizontal" role="form" action="<?php  echo BASE_URL;?>persons/index"	method="post">
	
				estoy aca?
</form>
 					</div>
 				</div>
 		</div>
 			<!-- no borrar -->
 			</div>
 			
 		</div>
 	</div>

 	
 	
 				
 					
 					
 					
 					