<div  class= "col-xs-9 col-sm-9 col-md-9 col-lg-9">
 				<div class= "panel panel-primary">
 					<div class= "panel-heading" style="background-color:#1C1C1C">
 						<h3 class= "panel-title"> Registros Generales </h3>
 					</div>
 					
 					<div class="panel-body">
		<form class="form-horizontal" role="form" action="<?php  echo BASE_URL;?>gestion/prestamo" method="post" name="registrop" id="registrop">
		
		<div class="form-group">
		<center>
		<button style="" type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Nuevo Edificio</button>
		</center>
  <!-- Trigger the modal with a button -->

  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Registrar Nuevo Edificio</h4>
        </div>
        <div class="modal-body">

	<div class="form-group">
		<label class="col-sm-3 control-label">Nombre Edificio:</label>
		<div class="col-sm-7">
			<input type="text" class="form-control" id="nombre" name="nombre" placeholder="Nombre" required> 
		</div>
	</div>

        </div>
        <div class="modal-footer">
        <center>
		<button type="button" class="btn btn-primary" onclick="registrarEdificio()"> Registrar </button>
		</center>
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>
	</div>					
		
		<div class="form-group">
		<center>
		<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal2">Nuevo Piso</button>
		</center>
  <!-- Trigger the modal with a button -->

  <!-- Modal -->
  <div class="modal fade" id="myModal2" role="dialog">
    <div class="modal-dialog modal-lg">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Registrar Nuevo Piso</h4>
        </div>
        <div class="modal-body">

        	<div class="form-group">

		<label class="col-sm-3 control-label">Edificio:</label>
		<div class="col-sm-7">
			<select id="edificio" name="edificio" class="form-control" required>
			</select>			
		</div>
	</div>
	
	<div class="form-group">
		<label class="col-sm-3 control-label">Nombre Piso:</label>
		<div class="col-sm-7">
			<input type="text" class="form-control" id="nombrePiso" name="nombrePiso" placeholder="Nombre" required> 
		</div>
	</div>
	 	  	
		 <center>
		<button type="button" class="btn btn-primary" onclick="registrarPiso()"> Registrar </button>
		</center>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>

    </div>
  </div>
	</div>				

	<div class="form-group">
		<center>
		<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal3">Nueva Habitacion</button>
		</center>
  <!-- Trigger the modal with a button -->

  <!-- Modal -->
  <div class="modal fade" id="myModal3" role="dialog">
    <div class="modal-dialog modal-lg">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Nueva Habitacion</h4>
        </div>
        <div class="modal-body">

        	<div class="form-group">

		<label class="col-sm-3 control-label">Edificio:</label>
		<div class="col-sm-7">
			<select id="edificioH" name="edificioH" class="form-control" required>
			</select>			
		</div>
	</div>

	<div class="form-group">

		<label class="col-sm-3 control-label">Piso:</label>
		<div class="col-sm-7">
			<select id="piso" name="piso" class="form-control" required>
						<option value="0">SELECCIONE</option>
			</select>			
		</div>
	</div>
	
	<div class="form-group">
		<label class="col-sm-3 control-label">Nombre Habitacion:</label>
		<div class="col-sm-7">
			<input type="text" class="form-control" id="nombreHabitacion" name="nombreHabitacion" placeholder="Nombre" required> 
		</div>
	</div>
	 	  	
		 <center>
		<button type="button" class="btn btn-primary" onclick="registrarHabitacion()"> Registrar </button>
		</center>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>

    </div>
  </div>
	</div>				

	<div class="form-group">
		<center>
		<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal4">Nueva Cama</button>
		</center>
  <!-- Trigger the modal with a button -->

  <!-- Modal -->
  <div class="modal fade" id="myModal4" role="dialog">
    <div class="modal-dialog modal-lg">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Registrar Nueva Cama</h4>
        </div>
        <div class="modal-body">

        	<div class="form-group">

		<label class="col-sm-3 control-label">Edificio:</label>
		<div class="col-sm-7">
			<select id="edificioC" name="edificioC" class="form-control" required>
			</select>			
		</div>
	</div>

	<div class="form-group">

		<label class="col-sm-3 control-label">Piso:</label>
		<div class="col-sm-7">
			<select id="pisoC" name="pisoC" class="form-control" required>
						<option value="0">SELECCIONE</option>
			</select>			
		</div>
	</div>

		<div class="form-group">

		<label class="col-sm-3 control-label">Habitacion:</label>
		<div class="col-sm-7">
			<select id="habitacion" name="habitacion" class="form-control" required>
						<option value="0">SELECCIONE</option>
			</select>			
		</div>
	</div>
	
	<div class="form-group">
		<label class="col-sm-3 control-label">Nombre Cama:</label>
		<div class="col-sm-7">
			<input type="text" class="form-control" id="nombreCama" name="nombreCama" placeholder="Nombre" required> 
		</div>
	</div>
	 	  	
		 <center>
		<button type="button" class="btn btn-primary" onclick="registrarCama()"> Registrar </button>
		</center>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>

    </div>
  </div>
	</div>	

		<div class="form-group">
		<center>
		<button style="" type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal5">Nuevo Edificio</button>
		</center>
  <!-- Trigger the modal with a button -->

  <!-- Modal -->
  <div class="modal fade" id="myModal5" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Nueva Disciplina</h4>
        </div>
        <div class="modal-body">

	<div class="form-group">
		<label class="col-sm-3 control-label">Disciplina:</label>
		<div class="col-sm-7">
			<input type="text" class="form-control" id="disciplina" name="disciplina" placeholder="Nombre" required> 
		</div>
	</div>

        </div>
        <div class="modal-footer">
        <center>
		<button type="button" class="btn btn-primary" onclick="registrarDisciplina()"> Registrar </button>
		</center>
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>
	</div>				

</form>



 					
 				
 		</div>
 			<!-- no borrar -->
 			</div>
 			
 		</div>
 	</div>

 	
 	
 				
 					
 					
 					
 					