
 			<div  class= "col-xs-9 col-sm-9 col-md-9 col-lg-9">
 				<div class= "panel panel-primary">


		                    <div class="panel-body">
		
 					
 				
						<table id="tabla" class="table" cellspacing="0" width="100%">
							<thead>
									<center>
									<tr>
										<th>#</th>
										<th>Nombre</th>
										<th>Plan Asociado</th>
										<th colspan="1"><center>Opciones</center></th>
								</tr>
								</center>
							</thead>
						
						</table>	 

<div class="modal fade" id="myModal" role="dialog">
  <div class="modal-dialog modal-lg">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
         <center><h4 class="modal-title">Asignar Plan</h4></center>
      </div>
      <div class="modal-body">
         
			<label class="col-sm-1 control-label">Nombre del hotel:</label>
		<div class="col-sm-2">
			<input type="text" id="nombre" onkeypress="return validanum(event)" class="form-control" name="nombre" placeholder="Nombre" disabled> 
		</div>


			<table id="tabla3" class="display" cellspacing="0" width="100%">
							<thead>
									<tr>
										<th>Nombre</th>
										<th>Descripcion</th>
										<th>Precio</th>
										<th>Fecha Facturacion</th>
										<th>Moneda</th>
										<th>Frecuencia</th>
										<th>Opciones</th>
								</tr>
							</thead>
			</table>
				
	

    		
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Listo</button>
      </div>
    </div>
  </div>
</div> 		

 				</div>	  	
 			
	 	  </div>




 					</div>
 				</div>
 			<!-- no borrar -->
 			</div>
 			
 		</div>
 	</div>

 	
 	
 				
 					
 					
 					
 					