
 			<div  class= "col-xs-9 col-sm-9 col-md-9 col-lg-9">
 				<div class= "panel panel-primary">



		                    <div class="panel-body">
		 						
		 						<P ALIGN="justify"><big><b>1) En esta modulo se podra realizar el registro de las personas que hacen vida en la institucion , profesores, alumnos y personal obrero para poder recibir los prestamos en la pestaña persona</big></b>
		 						<br>
		 						<br>
		 						<P ALIGN="justify"><big><b>2) Tambien se podra registrar los articulos bibliograficos, no bibliograficos y materiales</big></b>

		 					</div>

 				
 					</div>
 				</div>
 		</div>
 			<!-- no borrar -->
 			</div>
 			
 		</div>
 	</div>

 	
 	
 				
 					
 					
 					
 					