 	<div  class= "col-xs-12 col-sm-12 col-md-12 col-lg-12">
 				<div class= "panel panel-primary">
 					<div class= "panel-heading">
 						<h3 class= "panel-title"> LISTA DE PERSONAS </h3>
 					</div>
 					
 					<div class="panel-body">
 					
 						
					<?php  if (isset($this->_listado )&& count($this->_listado)):?>
						<table class="table table-bordered table-hover">
							<thead>
									<tr>
										<th>#</th>
										<th>Nombre</th>
										<th>Apellido</th>
										<th>Cedula</th>
									<th colspan="3">Acciones</th>
								</tr>
							</thead>
							<tbody>
							<?php  for ($i=0; $i < count($this->_listado); $i++):?>
								<?php if(!$this->_listado[$i]['cedula'] == 0) :?>
									<tr>
											<td><?php echo $i+1;?></td>
											<td><?php echo $this->_listado[$i]['nombre'] ?></td>
											<td><?php echo $this->_listado[$i]['apellido'] ?></td>
											<td><?php echo $this->_listado[$i]['cedula'] ?></td>
											<td>
												<a href="<?php echo BASE_URL .'persons/update/'.$this->_listado[$i]['idpersona'];?>">
													<span class="glyphicon glyphicon-cog" data-toggle="tooltip" title="actualizar"></span>
												</a>
											</td>
											<td>
												<a href="<?php echo BASE_URL .'persons' . DS . 'delete' . DS . $this->_listado[$i]['idpersona'];?>">
													<span class="glyphicon glyphicon-trash" data-toggle="tooltip" title="eliminar"> </span>
												</a>
											</td>
											<td>
												<a href="<?php echo BASE_URL .'persons' . DS . 'asignar' . DS . $this->_listado[$i]['idpersona'];?>">
													<span class="glyphicon glyphicon-plus" data-toggle="tooltip" title="asignar a un grupo"> </span>
												</a>
											</td>
					<?php endif;?>
						   <?php endfor;?>
						   </tbody>
						</table>
					<?php else:?>
							<pre>No existen registros en la base de datos</pre>
					<?php endif;?>
	 	  	
	 	  </div>
	</div>
	
	</div>
	
	</div>
	
 </div>
</div>
 									 
 												
 										
 					
 					
 					
 	