<div class="form-horizontal">
	<div  class= "col-xs-12 col-sm-12 col-md-12 col-lg-12">
	  <div class= "panel panel-primary"  style="border:0; background-color:#E2EFF8">
          <div class= "panel-heading" style="background-color:#7DB4D0 ;color:#fff; border:0;">
 						<center><h3 class= "panel-title"> Consulta </h3></center>
 					</div>
 					<div class="panel-body">
 					
<div class= "col-xs-3 col-sm-3 col-md-3 col-lg-3">
<div class="col-md-4 col-lg-4"></div>
<div class="col-md-4 col-lg-4"></div>
<div class="col-md-4 col-lg-4"></div>
</div>
 			<div  class= "col-xs-6 col-sm-6 col-md-6 col-lg-6">
        <div class= "panel panel-primary"  style="border:0;border-bottom: 0px" id="panel1">
          <div class= "panel-heading" style="background-color:#7DB4D0 ;color:#fff; border:0; border-bottom: 0px">
 						<a align="left" onclick="ocultar('1');">ocultar</a><center><h3 class= "panel-title"> Buscar</h3></center>
 					</div>
 					
 					<div class="panel-body" style="border-bottom: 0px">

<form name="nombre" enctype="multipart/form-data" id="nombre2" method="post" action="<?php  echo BASE_URL;?>consulta/imagen">

	<div class="form-group" >
		<label class="col-sm-5 control-label">Cedula:</label>
		<div class="col-sm-5">
			<input type="text" id="cedula" onkeypress="return validanum(event)" class="form-control" name="cedula" placeholder="Cedula"> 
		</div>
	</div>
	

	<div><center>
		<button type="button" class="btn btn-info" onclick="validar_consulta()"> Consultar </button>
	</center>
	</div>

				
 		</div>
 	</div>
 		</div>

 		<div  class= "col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class= "panel panel-primary"  style="border:0;" id="panel2">
          <div id="seccion1" class= "panel-heading" style="background-color:#7DB4D0   ;color:#fff;border:0;">
 						<a align="left" onclick="ocultar('2');">ocultar</a><center><h3 class= "panel-title"> Datos de la Persona </h3></center>
 		</div>
 					
 					<div class="panel-body">
 					 		<br>

 	
	<div class="form-group">

		<label class="col-sm-1 control-label">Nombre:</label>
		<div class="col-sm-2">
			<input type="text" id="nombre" onkeypress="return validanum(event)" class="form-control" name="nombre" placeholder="Nombre" disabled> 
		</div>

		<label class="col-sm-1 control-label">Apellido:</label>
		<div class="col-sm-2">
			<input type="text" id="apellido" onkeypress="return validanum(event)" class="form-control" name="apellido" placeholder="Apellido" disabled> 
		</div>

		
	<label class="col-sm-1 control-label">Edad:</label>
		<div class="col-sm-2">
			<input type="text" id="edad" onkeypress="return validanum(event)" class="form-control" name="edad" placeholder="Edad" disabled> 
		</div>

		<label class="col-sm-1 control-label">Sexo:</label>
		<div class="col-sm-2">
			<input type="text" id="sexo" class="form-control" name="sexo" disabled placeholder="Sexo"> 
		</div>
	</div>

 </div>
 		</div>

 		



 		<div  class= "col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class= "panel panel-primary"  style="border:0;" id="panel3">
          <div id="seccion2" class= "panel-heading" style="background-color:#7DB4D0   ;color:#fff;border:0;">
 						<center><h3 class= "panel-title"> Buscar Disponibilidad </h3></center>
 					</div>
 					
 					<div class="panel-body">

	<div class="form-group" >
		
	

 		<div  class= "col-xs-4 col-sm-4 col-md-4 col-lg-4" >
        <div class= "panel panel-primary"  style="border:0;" id="panel4">
          <div id="seccion3" class= "panel-heading" style="background-color:#7DB4D0   ;color:#fff; border:0;">
 						<center><h3 class= "panel-title"> Edificio </h3></center>
 					</div>
 					
 					<div class="panel-body">

<div class="form-group">
		<label class="col-sm-3 control-label">Edificio:</label>
		<div class="col-sm-8" id="tratamiento">
			<select style="height: 40px" id="hEdificio" name="hEdificio" class="form-control">
					<option value="0">SELECCIONE</option>
			</select>
		</div>
	</div>
	 					</div>
 				</div>
 		</div>

 		<div  class= "col-xs-4 col-sm-4 col-md-4 col-lg-4">
        <div class= "panel panel-primary"  style="border:0;" id="panel5">
          <div id="seccion4" class= "panel-heading" style="background-color:#7DB4D0   ;color:#fff; border:0;">
 						<center><h3 class= "panel-title"> Piso </h3></center>
 					</div>
 					
 					<div class="panel-body">
 						<div class="form-group">
						<label class="col-sm-3 control-label">Pisos:</label>
						<div class="col-sm-8" id="datos2">
					<select style="height: 40px" id="hPiso" name="hPiso" class="form-control">
						<option value="0">SELECCIONE</option>
					</select>
						</div>	
						</div>
					</div>
		

	 					</div>
 				</div>

 				 		<div  class= "col-xs-4 col-sm-4 col-md-4 col-lg-4">
        <div class= "panel panel-primary"  style="border:0;" id="panel5">
          <div id="seccion4" class= "panel-heading" style="background-color:#7DB4D0   ;color:#fff; border:0;">
 						<center><h3 class= "panel-title"> Habitación</h3></center>
 					</div>
 					
 					<div class="panel-body">
 						<div class="form-group">
						<label class="col-sm-3 control-label">Habitación:</label>
						<div class="col-sm-8" id="datos2">
					<select style="height: 40px" id="hHabitacion" name="hHabitacion" class="form-control">
						<option value="0">SELECCIONE</option>
					</select>
						</div>	
						</div>
					</div>
	 					</div>
 				</div>

 						<div  class= "col-xs-12 col-sm-12 col-md-12 col-lg-12">
 						<center>
	 					<div  align="center"  class= "col-xs-4 col-sm-4 col-md-4 col-lg-4">
	 					<div class="well well-sm">
 						<div align="center">Adjuntar Imagen:</div>
          				<a class="glyphicon glyphicon-level-up fa-2x" id="a" data-toggle="modal" data-target="#myModal4" title="Cargar imagen"></a> 
 						</div>
 						</div>
 						<div align="center" class= "col-xs-4 col-sm-4 col-md-4 col-lg-4" id="divver">
	 					<div class="well well-sm">
 						<div align="center">Ver Imagenes:</div>
          				<a class="glyphicon glyphicon-picture fa-2x" onclick="carga1();" data-toggle="modal" data-target="#myModal5"></a> 
 						</div>
 						</div>	
 						<div  class= "col-xs-4 col-sm-4 col-md-4 col-lg-4" id="divreporte">
	 					<div class="well well-sm">
 						<div align="center">Reporte de consulta</div>
          				<a class="glyphicon glyphicon-list-alt fa-2x" onclick="report1();"> <a> 
 						</div>
 						</div>
 						</center>	
 						<br>


<div class="modal fade" id="myModal4" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
         <center><h4 class="modal-title">Agregar Imagen</h4></center>
      </div>
      <div class="modal-body">
         
			<label for="imagen">Imagen:</label>
              <input class="form-control" type="file" name="hugo" id="imagen" /> 
        	<br>
        	<div class="form-group" >
		<label class="col-sm-5 control-label">Descripcion:</label>
		<div class="col-sm-5">
			<input type="text" id="descripcion" class="form-control" name="descripcion" placeholder="descripcion"> 
		</div>
	</div>

        </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Listo</button>
      </div>
    </div>

  </div>
</div> 		

<div class="modal fade" id="myModal5" role="dialog">
  <div class="modal-dialog modal-lg">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
         <center><h4 class="modal-title">Ver Imagen</h4></center>
      </div>
      <div class="modal-body">
         
			<label for="imagen">Imagenes:</label>
				
	
		
  <div class="row" id="imagenes1">


    
  </div>

    		
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Listo</button>
      </div>
    </div>
  </div>
</div> 								
</div>


<div class= "col-xs-12 col-sm-12 col-md-12 col-lg-12">
	<div class= "col-xs-3 col-sm-3 col-md-3 col-lg-3">
 						<div align="center">Consulta anterior</div>
          				<center>
          				<a class="glyphicon glyphicon-arrow-left fa-2x" onclick="siguiente()"></a>
          				</center>
    </div>
    <div class= "col-xs-6 col-sm-6 col-md-6 col-lg-6">
	<center>
		<input type="submit" class="btn btn-info" id="registrar_consulta" value="Registrar Consulta"></input>
	</center>
	</div>
	 <div class= "col-xs-3 col-sm-3 col-md-3 col-lg-3">
 			
 						<div align="center">Consulta siguiente</div>
 						<center>
          				<a class="glyphicon glyphicon-arrow-right fa-2x" onclick="anterior()"></a>
          				</center>
    </div>
</div>

</form>

 				</div>
 				</div>
</div>


 			<!-- no borrar -->
 			</div>
 			
 		</div>
 	</div>