
 			<div  class= "col-xs-9 col-sm-9 col-md-9 col-lg-9">
 				<div class= "panel panel-primary">

<form class="form-horizontal" role="form" id="planes">
		                    <div class="panel-body">
		
 					
 				
						<table id="tablapersona" class="display" cellspacing="0" width="100%">
							<thead>
									<tr>
										<th>Nombre</th>
										<th>Apellido</th>
										<th>Fecha Nacimiento</th>
										<th>Cedula</th>
										<th>Sexo</th>
										<th>Disciplina</th>
										<th>Tipo</th>
								</tr>
							</thead>
			</table>

			 <div class="modal fade" id="myModalplan" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header" style="background-color:#4FBAF0">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title"> <font color="#fff"> Actualizar plan </font></h4>
        </div>
        <div class="modal-body">

         <div class="form-group">
		<label class="col-sm-3 control-label">Nombre:</label>
		<div class="col-sm-5">
			<input type="text" class="form-control" name="nombre" placeholder="Nombre" required> 
		</div>
	</div>

	<div class="form-group">
		<label class="col-sm-3 control-label">Descripcion:</label>
		<div class="col-sm-5">
			<input type="text" class="form-control" name="descripcion" placeholder="descripcion" required> 
		</div>
	</div>

	<div class="form-group" id="divmoneda">

		<label class="col-sm-3 control-label">Moneda de facturacion:</label>
		<div class="col-sm-5">
			<select id="moneda" name="moneda" class="form-control" required>
			</select>			
		</div>
	</div>

	<div class="form-group">
		<label class="col-sm-3 control-label">Monto:</label>
		<div class="col-sm-5">
			<input id="monto" type="text" class="form-control" onKeyPress="return soloNumeros(event)" name="monto" placeholder="Monto" required> 
		</div>
	</div>

		<div class="form-group" id="divfrecuencia">

		<label class="col-sm-3 control-label">Frecuencia de facturacion:</label>
		<div class="col-sm-5">
			<select id="frecuencia" name="frecuencia" class="form-control" required>
			</select>			
		</div>
	</div>
	
	

	<center>
		<button type="button" class="btn btn-info" id="registrar"> Registrar </button>
	</center>
        </div>
        <div class="modal-footer" style="background-color:#1a4a6d">
          <button type="button" class="btn btn-default" style="background-color:#fff" data-dismiss="modal" >Close</button>
        </div>
      </div>
      
    </div>
  </div>
  	
 			
	 	  </div>

</form>


 					</div>
 				</div>
 			<!-- no borrar -->
 			</div>
 			
 		</div>
 	</div>

 	
 	
 				
 					
 					
 					
 					