
<div  class= "col-xs-9 col-sm-9 col-md-9 col-lg-9">
 				<div class= "panel panel-primary">
 					<div class= "panel-heading">
 						<center>
 						<h3 class= "panel-title"> Nueva Persona </h3>
 						</center>
 					</div>
 					
 					<div class="panel-body">

<form id="registrar" class="form-horizontal" role="form" action="<?php  echo BASE_URL;?>persons/insert" method="post">
	
	<div class="form-group">
		<label class="col-sm-3 control-label">Nombre:</label>
		<div class="col-sm-5">
			<input type="text" class="form-control" name="nombre" placeholder="Nombre" required> 
		</div>
	</div>

	<div class="form-group">
		<label class="col-sm-3 control-label">Apellido:</label>
		<div class="col-sm-5">
			<input type="text" class="form-control" name="apellido" placeholder="Apellido" required> 
		</div>
	</div>

	<div class="form-group" id="divcedula">
		<label class="col-sm-3 control-label">Cedula de Identidad:</label>
		<div class="col-sm-5">
			<input onKeyPress="return soloNumeros(event)" class="form-control" name="cedula" placeholder="Cedula"> 
		</div>
	</div>

	<div class="form-group">
		<label class="col-sm-3 control-label">Fecha de Nacimiento:</label>
		<div class="col-sm-5">
			<input type="date" class="form-control" name="fecha_nacimiento" placeholder="Fecha de Nacimiento" required> 
		</div>
	</div>

		
<div class="form-group">

		<label class="col-sm-3 control-label">Sexo:</label>
		<div class="col-sm-5">
			<select id="sexo" name="sexo" class="form-control" required>
			</select>			
		</div>
	</div>


		<div class="form-group">

		<label class="col-sm-3 control-label">Tipo de persona:</label>
		<div class="col-sm-5">
			<select id="tipo" name="tipo" class="form-control" required>
			</select>			
		</div>
	</div>

	<div class="form-group"  style="display:none;" id="divdisciplina">

		<label class="col-sm-3 control-label">Disciplina:</label>
		<div class="col-sm-5">
			<select id="disciplina" name="disciplina" class="form-control" required>
			</select>			
		</div>
	</div>




	<center>
		<input type="submit" class="btn btn-primary" value="Registrar">
	</center>
			
 				
					
</form>
 										
 					
	</div>
 				</div>
 		</div>
 			<!-- no borrar -->
 			</div>
 			
 		</div>
 	</div>
