<div  class= "col-xs-9 col-sm-9 col-md-9 col-lg-9">
 				<div class= "panel panel-primary">
 					<div class= "panel-heading" style="background-color:#1C1C1C">
 						<h3 class= "panel-title"> Agregar articulos o materiales </h3>
 					</div>
 					
 					<div class="panel-body">
		<form class="form-horizontal" role="form" action="<?php  echo BASE_URL;?>persons/agregarbiblio" method="post">
		
		<div class="form-group">
		<center>
		<button style="" type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Agregar Articulo Bibligrafico</button>
		</center>
  <!-- Trigger the modal with a button -->

  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Agregar Articulo Bibliografico</h4>
        </div>
        <div class="modal-body">

         <div class="form-group">
		<label class="col-sm-4 control-label">Titulo:</label>
		<div class="col-sm-5">
			<input type="text" class="form-control" name="titulo" placeholder="Nombre" id="titulo"> 
		</div>
	</div>

	<div class="form-group">
		<label class="col-sm-4 control-label">Cota:</label>
		<div class="col-sm-5">
			<input type="text" class="form-control" name="cota" placeholder="Cota" id="Cota" required> 
		</div>
	</div>


	<div class="form-group">
		<label class="col-sm-4 control-label">Autores:</label>
		<div class="col-sm-5">
		<input type="text" class="form-control" name="busqueda" id="busqueda" value="" placeholder="" maxlength="30" autocomplete="off" onKeyup="buscar();">
			<br>
			<select multiple="multiple" id="autores" name="autores[]" class="form-control" required>
					<option value="0">SELECCIONE</option>
			</select>			
		</div>
	</div>


	<center>
		<button type="submit" class="btn btn-primary"> Registrar </button>
	</center>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>
	</div>					
</form>

<form class="form-horizontal" role="form" action="<?php  echo BASE_URL;?>persons/agregarnobiblio" method="post">
		
		<div class="form-group">
		<center>
		<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal3">Agregar Articulo No Bibligrafico</button>
		</center>
  <!-- Trigger the modal with a button -->

  <!-- Modal -->
  <div class="modal fade" id="myModal3" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Agregar Articulo No Bibliografico</h4>
        </div>
        <div class="modal-body">

         <div class="form-group">
		<label class="col-sm-4 control-label">Nombre:</label>
		<div class="col-sm-5">
			<input type="text" class="form-control" name="nombre" placeholder="Nombre" id="nombre"> 
		</div>
	</div>

	<div class="form-group">
		<label class="col-sm-4 control-label">Cantidad:</label>
		<div class="col-sm-5">
			<input type="text" class="form-control" name="cantidad" placeholder="Cantidad" id="cantidad" required> 
		</div>
	</div>

	<center>
		<button type="submit" class="btn btn-primary"> Registrar </button>
	</center>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>
	</div>					
</form>


<form class="form-horizontal" role="form" action="<?php  echo BASE_URL;?>persons/agregarmaterial" method="post">
		
		<div class="form-group">
		<center>
		<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal2">Agregar Materiales</button>
		</center>
  <!-- Trigger the modal with a button -->

  <!-- Modal -->
  <div class="modal fade" id="myModal2" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Agregar Materiales</h4>
        </div>
        <div class="modal-body">

         <div class="form-group">
		<label class="col-sm-4 control-label">Nombre:</label>
		<div class="col-sm-5">
			<input type="text" class="form-control" name="nombre" placeholder="Nombre" id="nombre"> 
		</div>
	</div>

	<center>
		<button type="submit" class="btn btn-primary"> Registrar </button>
	</center>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>
	</div>					
</form>




 					
 				
 		</div>
 			<!-- no borrar -->
 			</div>
 			
 		</div>
 	</div>

 	
 	
 				
 					
 					
 					
 					