<div  class= "col-xs-9 col-sm-9 col-md-9 col-lg-9">
 				<div class= "panel panel-primary">
 					<div class= "panel-heading">
 						<h3 class= "panel-title"> Nuevo Alumno </h3>
 					</div>
 					
 					<div class="panel-body">
		<form class="form-horizontal" role="form" action="<?php  echo BASE_URL;?>persons/semestre" method="post">
		<div class="form-group">
		<label class="col-sm-3 control-label">Escoja los semestres en que se encuentra:</label>
		<div class="col-sm-5" required>
					<input type="checkbox" name="numero" value="1" >1er semestre<br>
					<input type="checkbox" name="numero" value="2" >2do semestre<br>
					<input type="checkbox" name="numero" value="3" >3er semestre<br>
					<input type="checkbox" name="numero" value="4" >4to semestre<br>
					<input type="checkbox" name="numero" value="5" >5to semestre<br>
					<input type="checkbox" name="numero" value="6" >6to semestre<br>

		</div>

	</div>	

	
	<center>
		<br>
		<br>
		<input type="submit" class="btn btn-primary" value="Registrar">
	</center>
	

					
</form>
 					</div>
 				</div>
 		</div>
 			<!-- no borrar -->
 			</div>
 			
 		</div>
 	</div>

 	
 	
 				
 					
 					
 					
 					