<div  class= "col-xs-9 col-sm-9 col-md-9 col-lg-9">
 				<div class= "panel panel-primary">
 					<div class= "panel-heading">
 						<h3 class= "panel-title"> Actulizar Datos </h3>
 					</div>
 					
 					<div class="panel-body">

<form class="form-horizontal" role="form" action="<?php  echo BASE_URL;?>persons/update" method="post"  id="formulario" >
	<input type="text" hidden name="id" value="<?= $this->_persona[0]['idpersona'] ?>">
	<div class="form-group">
		<label class="col-sm-3 control-label">Nombre:</label>
		<div class="col-sm-5">
			<input type="text" class="form-control" name="nombre" placeholder="Nombre" value="<?= $this->_persona[0]['nombre'] ?>"required>
		</div>
	</div>

	<div class="form-group">
		<label class="col-sm-3 control-label">apellido:</label>
		<div class="col-sm-5">
			<input type="text" class="form-control" name="apellido" placeholder="Apellido" value="<?= $this->_persona[0]['apellido'] ?>"required> 
		</div>
	</div>

	<div class="form-group">
		<label class="col-sm-3 control-label">Cedula:</label>
		<div class="col-sm-5">
			<input type="text" class="form-control" name="cedula" placeholder="Cedula" value="<?= $this->_persona[0]['cedula'] ?>"required> 
		</div>
	</div>

	<center>
		<input type="submit" class="btn btn-primary" value="Guardar">
	</center>
	
 <span id="respuesta" name="respuesta"> </span>	
					
</form>
 					</div>
 				</div>
 		</div>
 			<!-- no borrar -->
 			</div>
 			
 		</div>
 	</div>

 	
 	
 				
 					
 					
 					
 					