  	<div  class= "col-xs-9 col-sm-9 col-md-9 col-lg-9">
 				<div class= "panel panel-primary">
 					<div class= "panel-heading">
 						<h3 class= "panel-title"> Estadisticas </h3>
 					</div>
 					
 					<div class="panel-body">
 					
 					<div class="form-group">
		<center>
		<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal2">Cantidad de actividades</button>
		</center>
  <!-- Trigger the modal with a button -->

  <!-- Modal -->
  <div class="modal fade" id="myModal2" role="dialog">
    <div class="modal-dialog modal-lg">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Actividades en el periodo <?php echo $this->_fechai.' Hasta '.$this->_fechaf ?> </h4>
        </div>
        <div class="modal-body">
      
	
	<?php  if (isset($this->_listado )&& count($this->_listado)):?>
						<table id="example"  style="text-align:center;" class="display" cellspacing="0" border="0" width="100%">
							<center>
							<thead>
									<tr>
										<th>Fecha</th>
										<th>actividad</th>
										<th>Cantidad Hombres</th>
										<th>Cantidad Mujeres</th>
										<th>Maestro</th>
										<th>Grado</th>
										<th>Seccion</th>
										<th>Materiales</th>
									</tr>
							</thead>
							<tbody>
							<?php  for ($i=0; $i < count($this->_listado); $i++):?>
								<?php if(!$this->_listado[$i]['fecha_act'] == 0) :?>
									<tr>
											<td><?php echo $this->_listado[$i]['fecha_act'] ?></td>
											<td><?php echo $this->_listado[$i]['nombre_actividad'] ?></td>
											<td><?php echo $this->_listado[$i]['can_varones'] ?></td>
											<td><?php echo $this->_listado[$i]['can_hembras'] ?></td>
											<td><?php echo $this->_listado[$i]['nombre1'] ?></td>
											<td><?php echo $this->_listado[$i]['grado'] ?></td>
											<td><?php echo $this->_listado[$i]['seccion'] ?></td>
											
  	<td><a href="#" title="Materiales usados" data-toggle="popover" data-trigger="focus" data-content="
  	<?php  for ($a=0; $a < count($this->_listado2); $a++):?>
  	<?php if($this->_listado2[$a]['idactividades'] == $this->_listado[$i]['idactividades'] ) :?>	
  	<?php echo $this->_listado2[$a]['nombre_material']?>
  	<?php endif;?>
	<?php endfor;?>">Ver</a></td>
</div>								
					<?php endif;?>
						   <?php endfor;?>
						   </tr>
						   </tbody>
						</table>
					<?php else:?>
							<pre>No existen registros en la base de datos</pre>
					<?php endif;?>
	 	  	
		
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>     
  </div>
	</div>	
	<br>

	<center>
		<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Total de alumnos</button>
		</center>
  <!-- Trigger the modal with a button -->

  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Total Hombres y Mujeres en Actividades desde<?php echo $this->_fechai.' Hasta '.$this->_fechaf ?> </h4>
        </div>
        <div class="modal-body">
	
	<?php  if (isset($this->_listado )&& count($this->_listado)):?>
						<table id="example"  style="text-align:center;" class="display" cellspacing="0" border="0" width="100%">
							<thead>
									<tr>
										<th>Total Hombres en actividades</th>
										<th>Total Mujeres en actividades</th>
									</tr>
							</thead>
							<tbody>
							<?php  for ($i=0; $i < count($this->_listado1); $i++):?>
								<?php if(!$this->_listado1[$i]['cantidad_hombres'] == 0) :?>
									<tr>
											<td><?php echo $this->_listado1[$i]['cantidad_hombres'] ?></td>
											<td><?php echo $this->_listado1[$i]['cantidad_mujeres'] ?></td>	
					<?php endif;?>
						   <?php endfor;?>
						   </tbody>
						</table>
					<?php else:?>
							<pre>No existen registros en la base de datos</pre>
					<?php endif;?>
	 	  	
		
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>					
	 	  </div>
</div>
 									 
 												
 										
 					
 					
 					
 	