<div  class= "col-xs-9 col-sm-9 col-md-9 col-lg-9">
 				<div class= "panel panel-primary">
 					<div class= "panel-heading">
 						<h3 class= "panel-title"> estadisticas </h3>
 					</div>
 					
 					<div class="panel-body">

<form class="form-horizontal" role="form" action="<?php  echo BASE_URL;?>estadistica/calcular" method="post">
	
	<div class="form-group">
		<label class="col-sm-4 control-label">Fecha Inicio:</label>
		<div class="col-sm-5">
			<input type="date" class="form-control" id="fechai" name="fechai" placeholder="Fecha Inicio" required> 
		</div>
	</div>

	<div class="form-group">
		<label class="col-sm-4 control-label">Fecha Fin:</label>
		<div class="col-sm-5">
			<input type="date" class="form-control" id="fechaf" name="fechaf" placeholder="Fecha Fin" required> 
		</div>
	</div>
	

	
	<center>
		<center>
		<input type="submit" class="btn btn-primary" value="Calcular">
	</center>
	</center>
	

					
</form>
 					</div>
 				</div>
 		</div>
 			<!-- no borrar -->
 			</div>
 			
 		</div>
 	</div>

 	
 	
 				
 					
 					
 		