<div  class= "col-xs-9 col-sm-9 col-md-9 col-lg-9">
 				<div class= "panel panel-primary">
 					<div class= "panel-heading">
 						<h3 class= "panel-title"> Nuevo Instrumento </h3>
 					</div>
 					
 					<div class="panel-body">

<form class="form-horizontal" role="form" action="<?php  echo BASE_URL;?>instrumento/insert" method="post">
	
	<div class="form-group">
		<label class="col-sm-3 control-label">Nombre Instrumento:</label>
		<div class="col-sm-5">
			<input type="text" class="form-control" name="instrumento" placeholder="Nombre" required> 
		</div>
	</div>

	<div class="form-group">
		<label class="col-sm-3 control-label">Tipo de instrumento:</label>
		<div class="col-sm-5">
			<select name="tipo" class="form-control" requied>
						<option value="1">Viento</option>
						<option value="2">Percusion</option>
						<option value="3">Cuerda</option>
			</select>			
		</div>
	</div>

	

	
	<center>
		<br>
		<br>
		<input type="submit" class="btn btn-primary" value="Registrar">
	</center>
	

					
</form>
 					</div>
 				</div>
 		</div>
 			<!-- no borrar -->
 			</div>
 			
 		</div>
 	</div>

 	
 	
 				
 					
 					
 					
 					