<div  class= "col-xs-9 col-sm-9 col-md-9 col-lg-9">
 				<div class= "panel panel-primary">
 					<div class= "panel-heading">
 						<h3 class= "panel-title"> Actulizar Datos </h3>
 					</div>
 					
 					<div class="panel-body">

<form class="form-horizontal" role="form" action="<?php  echo BASE_URL;?>instrumento/update" method="post">
	<input type="text" hidden name="id" value="<?= $this->_instrumento[0]['idinstrumentos'] ?>">
	<div class="form-group">
		<label class="col-sm-3 control-label">Nombre instrumento:</label>
		<div class="col-sm-5">
			<input type="text" class="form-control" name="instrumento" placeholder="Nombre" value="<?= $this->_instrumento[0]['instrumento'] ?>"required>
		</div>
	</div>

	<div class="form-group">
		<label class="col-sm-3 control-label">tipo instrumento:</label>
		<div class="col-sm-5">
			<select name="tipo" class="form-control" required>
						<option value="1">Viento</option>
						<option value="2">Percusion</option>
						<option value="5">Cuerda</option>
		</div>
	</div>

	
	<center>
		<input type="submit" class="btn btn-primary" value="Guardar">
	</center>
	

					
</form>
 					</div>
 				</div>
 		</div>
 			<!-- no borrar -->
 			</div>
 			
 		</div>
 	</div>


 	
 	
 				
 					
 					
 					
 					