
 			<div  class= "col-xs-9 col-sm-9 col-md-9 col-lg-9">
 				<div class= "panel panel-primary">

 						<div class="panel-body">
		 						
		 						<P ALIGN="justify"><big><b>1) En este modulo podemos realizar los prestamops de articulos a las personas previamente registradas en el sistema en la pestaña prestamo</big></b>
		 						<br>
		 						<br>
		 						<P ALIGN="justify"><big><b>2) Tambien se podra registrar las actividades a realizar en la biblioteca en la pestaña actividad</big></b>

		 					</div>
 					
        
 					</div>
 				</div>
 		</div>
 			<!-- no borrar -->
 			</div>
 			
 		</div>
 	</div>

 	
 	
 				
 					
 					
 					
 					