<div  class= "col-xs-9 col-sm-9 col-md-9 col-lg-9">
 				<div class= "panel panel-primary">
 					<div class= "panel-heading">
 						<h3 class= "panel-title"> LISTA DE INSTRUMENTOS </h3>
 					</div>
 					
 					<div class="panel-body">
 					
 					<div class="well well-sm">
 					
 			<form class="form-inline"  role="form" method="post" action="<?php  echo BASE_URL;?>instrumento/listing">
 				<input type="hidden" name="save" value="1" />
 						<div class="form-group col-xs-5">
 					<input type="text" class="form-control" name="criterial" id="criterial" placeholder="Buscar
 					Registro">
 										</div>
 										<input type="submit" class="btn btn-primary" value="Buscar" />
 			</form>
 								
 						</div>
 						
					<?php  if (isset($this->_listado )&& count($this->_listado)):?>
						<table class="table table-bordered table-hover">
							<thead>
									<tr>
										<th>#</th>
										<th>Instrumento</th>
										<th>Tipo de Instrumento</th>
									<th colspan="3">Acciones</th>
								</tr>
							</thead>
							<tbody>
							<?php  for ($i=0; $i < count($this->_listado); $i++):?>
								<?php if(!$this->_listado[$i]['instrumento'] == 0) :?>
									<tr>
											<td><?php echo $i+1;?></td>
											<td><?php echo $this->_listado[$i]['instrumento'] ?></td>
											<td><?php echo $this->_listado[$i]['tipo_instrumento'] ?></td>
											<td>
												<a href="<?php echo BASE_URL .'grupo/asignar/'.$this->_idgrupo.'/'.$this->_listado[$i]['idinstrumentos'];?>">
													<span class="glyphicon glyphicon-plus" data-toggle="tooltip" title="asignar grupo"></span>
												</a>
											</td>
					<?php endif;?>
						   <?php endfor;?>
						   </tbody>
						</table>
					<?php else:?>
							<pre>No existen registros en la base de datos</pre>
					<?php endif;?>
	 	  	
	 	  </div>
	</div>
	
	</div>
	
	</div>
	
 </div>
</div>