 	<div  class= "col-xs-9 col-sm-9 col-md-9 col-lg-9">
 				<div class= "panel panel-primary">
 					<div class= "panel-heading">
 						<h3 class= "panel-title"> LISTA DE GRUPOS </h3>
 					</div>
 					
 					<div class="panel-body">
 					
 						
					<?php  if (isset($this->_listado )&& count($this->_listado)):?>
						<table class="table table-bordered table-hover">
							<thead>
									<tr>
										<th>#</th>
										<th>Nombre</th>
										<th>Limite de personas</th>
										<th>Instrumento</th>
										<th>tipo Instrumento</th>
										<th>Actividad</th>
									<th colspan="4">Acciones</th>
								</tr>
							</thead>
							<tbody>
							<?php  for ($i=0; $i < count($this->_listado); $i++):?>
								<?php if(!$this->_listado[$i]['nombre_grupo'] == 0) :?>
									<tr>
											<td><?php echo $i+1;?></td>
											<td><?php echo $this->_listado[$i]['nombre_grupo'] ?></td>
											<td><?php echo $this->_listado[$i]['limite_personas'] ?></td>
											<td><?php echo $this->_listado[$i]['instrumento'] ?></td>
											<td><?php echo $this->_listado[$i]['tipo_instrumento'] ?></td>
											<td><?php echo $this->_listado[$i]['actividad'] ?></td>
											<td>
												<a href="<?php echo BASE_URL .'grupo/update/'.$this->_listado[$i]['idgrupo'];?>">
													<span class="glyphicon glyphicon-cog" data-toggle="tooltip" title="actualizar"></span>
												</a>
											</td>
											<td>
												<a href="<?php echo BASE_URL .'grupo' . DS . 'delete' . DS . $this->_listado[$i]['idgrupo'];?>">
													<span class="glyphicon glyphicon-trash" data-toggle="tooltip" title="eliminar"> </span>
												</a>
											</td>
											<td>
												<a href="<?php echo BASE_URL .'grupo' . DS . 'asignar' . DS . $this->_listado[$i]['idgrupo'];?>">
													<span class="glyphicon glyphicon-plus" data-toggle="tooltip" title="asignar instrumento"> </span>
												</a>
											</td>
											<td>
												<a href="<?php echo BASE_URL .'grupo' . DS . 'asignar1' . DS . $this->_listado[$i]['idgrupo'];?>">
													<span class="glyphicon glyphicon-plus" data-toggle="tooltip" title="asignar actividad"> </span>
												</a>
											</td>
							
					<?php endif;?>
						   <?php endfor;?>
						   </tbody>
						</table>
					<?php else:?>
							<pre>No existen registros en la base de datos</pre>
					<?php endif;?>
	 	  	
	 	  </div>
	</div>
	
	</div>
	
	</div>
	
 </div>
</div>
 									 
 												
 										
 					
 					
 					
 	