<div  class= "col-xs-9 col-sm-9 col-md-9 col-lg-9">
 				<div class= "panel panel-primary">
 					<div class= "panel-heading">
 						<h3 class= "panel-title"> Actulizar Datos </h3>
 					</div>
 					
 					<div class="panel-body">

<form class="form-horizontal" role="form" action="<?php  echo BASE_URL;?>grupo/update" method="post">
	<input type="text" hidden name="id" value="<?= $this->_grupo[0]['idgrupo'] ?>">
	<div class="form-group">
		<label class="col-sm-3 control-label">Nombre:</label>
		<div class="col-sm-5">
			<input type="text" class="form-control" name="nombre" placeholder="Nombre" value="<?= $this->_grupo[0]['nombre_grupo'] ?>"required>
		</div>
	</div>

	<div class="form-group">
		<label class="col-sm-3 control-label">limite de personas:</label>
		<div class="col-sm-5">
			<input type="text" class="form-control" name="limite" placeholder="Apellido" value="<?= $this->_grupo[0]['limite_personas'] ?>"required> 
		</div>
	</div>

	
	<center>
		<input type="submit" class="btn btn-primary" value="Guardar">
	</center>
	

					
</form>
 					</div>
 				</div>
 		</div>
 			<!-- no borrar -->
 			</div>
 			
 		</div>
 	</div>

 	
 	
 				
 					
 					
 					
 					