   

    <!-- jQuery -->
    <script src="<?php echo PUBLIC_URL;?>plantilla1/js/jquery.js"></script>
     <script src="<?php echo PUBLIC_URL;?>js/jquery-2.1.4.js"></script>
    <script src="<?php echo PUBLIC_URL;?>plantilla1/js/funcionesgestion.js"></script>
     <script type="text/javascript" language="javascript" src="<?php echo PUBLIC_URL;?>plantilla1/js/jquery.dataTables.min.js">
    </script>
    <script type="text/javascript" language="javascript" src="<?php echo PUBLIC_URL;?>plantilla1/js/sweetalert.min.js">
    </script>
    <!-- Bootstrap Core JavaScript -->
    <script src="<?php echo PUBLIC_URL;?>plantilla1/js/bootstrap.min.js"></script>
    

    <!-- Script to Activate the Carousel -->
    <script>
    $('.carousel').carousel({
        interval: 5000 //changes the speed
    })
    </script>


</body>

</html>