<div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
					<div class="list-group">
						<a  class="list-group-item active">Opciones</a>
						
						<?php  if ($_view_params['sidebar_menu']):?>
						<?php for ($i = 0; $i < count($_view_params['sidebar_menu']); $i++):?>
<a href="<?php echo $_view_params['sidebar_menu'][$i]['link']; ?>"class="list-group-item"><?php echo $_view_params['sidebar_menu'][$i]['title'];?></a> 
						<?php endfor;?>
						<?php endif;?>
						
						
				</div>
				</div>
				
				
				