<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>IND</title>


    <link rel="shortcut icon" href="<?php echo PUBLIC_URL;?>plantilla1/img/paxer-logo-footer.png"><!--imagen del explorador-->
    <!-- Bootstrap Core CSS -->
      <link href="<?php echo PUBLIC_URL;?>css/bootstrap.css" rel="stylesheet">
      <link rel="stylesheet" href="<?php echo PUBLIC_URL;?>plantilla1/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="<?php echo PUBLIC_URL;?>plantilla1/css/jquery.dataTables.min.css">
    <!-- Custom CSS -->
    <link href="<?php echo PUBLIC_URL;?>plantilla1/css/busines-casual.css" rel="stylesheet">
    <link href="<?php echo PUBLIC_URL;?>plantilla1/css/datatables.min.css" rel="stylesheet">
    <link href="<?php echo PUBLIC_URL;?>plantilla1/css/sweetalert.css" rel="stylesheet">

    <!-- Fonts 
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">

    <link href="https://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">-->

   
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body class="home" style="background-color:#0B243B">

    <div class="brand">Control de acceso y disponibilidad I.N.D</div> 
    
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
     <center>
      <img src="<?php echo PUBLIC_URL;?>plantilla1/img/primer-slide.jpg" width="1145" height="325" alt="Chania">
     </center>
    </div>

    <div class="item">
      <center>
      <img src="<?php echo PUBLIC_URL;?>plantilla1/img/segundo-slide.jpeg" width="1145" height="325" alt="Chania">
      </center>
    </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Anterior</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Siguiente</span>
  </a>
</div>
</div>
    
     